version: '3'
services:
  auth:
    build: ./Auth
    container_name: auth-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb://mongo:27017/Authentification_Autorisation
    depends_on:
      - mongo
  
  project:
    build: ./Project
    container_name: project-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_URI=mongodb://mongo:27017/gestion_projet
    depends_on:
      - mongo

  tasks:
    build: ./Tasks
    container_name: task-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo:27017/task-manager
    depends_on:
      - mongo


  chats:
    build: ./chat
    container_name: chat-service
    ports:
      - "6000:6000"
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo:27017/chat
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
